# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c03a07b823cc1ef6dd5327433053eec1415ce8f396890d2a6a04d85d5762a9088f7750451594d4539e22864f135da411efff287baa643a0643bc787ea1ec5932

test:
  secret_key_base: 9e6b0c54876e8afcd293c5510b786a2621b8147c5fbdd1b24232c89980bef09f937a50109b798fbc36398ea5535dede4e8c90feb259c1d3b5cec08d59714ce6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
